### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by Aidrocker** [Aidrocker/demo-1.1#1]
@coursar проверить дз
https://github.com/Aidrocker/demo-1.1/blob/254ee20d8cc3333e30a80bdb2d560a8105245150/dz%201%2C1.js#L1-L9

**Comment by coursar** [comment]
1. Имена переменных с маленькой буквы

**Comment by coursar** [comment]
Всё ок, теперь нужно писать тесты.
